#!/bin/bash

NAME=bleh_$(date -u +"%Y-%m-%d_%H-%M-%S").png
URL=https://jakob.su/screenshots/$NAME
echo $URL | xclip -selection clipboard
echo $URL
scrot -s -o /dev/stdout | ssh do "cat > /srv/http/screenshots/$NAME"
