add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[gcloud]
disabled = true

[hg_branch]
disabled = true

[battery]
disabled = true

[docker_context]
disabled = true

[cmake]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[username]
disabled = true

[helm]
disabled = true
