set nocompatible
filetype off

let s:editor_root=expand("~/.vim")

" Setting up Vundle - the vim plugin bundler
let vundle_installed=1
let vundle_readme=s:editor_root . '/bundle/vundle/README.md'
if !filereadable(vundle_readme)
    echo "Installing Vundle.."
    echo ""
    " silent execute "! mkdir -p ~/." . s:editor_path_name . "/bundle"
    silent call mkdir(s:editor_root . '/bundle', "p")
    silent execute "!git clone https://github.com/gmarik/vundle " . s:editor_root . "/bundle/vundle"
    let vundle_installed=0
endif
let &rtp = &rtp . ',' . s:editor_root . '/bundle/vundle/'
call vundle#rc(s:editor_root . '/bundle')

" Let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'
Plugin 'mileszs/ack.vim'
Plugin 'mnpk/vim-jira-complete'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdcommenter'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tomasr/molokai'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'mxw/vim-jsx'

if vundle_installed == 0
    :BundleInstall
endif

filetype plugin indent on

" Toggle paste mode (no auto indent) with f2
set pastetoggle=<f2>

" , as extra modifier key (Leader)
let mapleader = ","

" Leader-h to show hidden chars
nmap <leader>h :set list!<CR>

" Arrow keys to resize split windows
map <Up> <C-W>+
map <Down> <C-W>-
map <Left> <C-W><
map <Right> <C-W>>

" §j §k §l §ö to navigate split windows
map §j <C-W>h
map §k <C-W>j
map §l <C-W>k
map §ö <C-W>l

" Leader-s to sort selected lines e.g. to sort python imports alphabetically
vnoremap <Leader>s :sort<CR> 

" Q wraps paragraph
vmap Q gq
nmap Q gqap

" Do not deselect when indenting
vnoremap < < gv
vnoremap > > gv

" Syntax highlighting
filetype off
filetype plugin indent on
syntax on

" Textwidth - Maximum width of text that is being inserted.  A longer line will
" be broken after white space to get this width.  A zero value disables  
" set tw=79

" Don't wrap lines
set nowrap

" Hilight line 80
set fo-=t
set colorcolumn=80
highlight ColorColumn ctermbg=DarkGray

" BAM your <Tab> and <Backspace> keys are convenient now without the pain
" associated with \t characters in source files
set shiftwidth=4
set softtabstop=4 expandtab

" Don't add newlines at ends of files
set fileformats+=dos

" Save >9k actions in undo history
set undolevels=9001

" Highlight all search results
set hlsearch

" ,l redraws the screen and removes any search highlighting. 
nnoremap <silent> <Leader>l :nohl<CR>

" Search while typing
set incsearch

" When 'ignorecase' and 'smartcase' are both on, if a pattern contains an
" uppercase letter, it is case sensitive, otherwise, it is not. For example,
" /The would find only "The", while /the would find "the" or "The" etc.
set ignorecase
set smartcase

" UTF-8!
if &modifiable
    set encoding=utf-8
    set fileencoding=utf-8
    set fileencodings=utf-8
endif

" No beepin'
set vb t_vb=

" Center cursor vertically
set scrolloff=999

" Toggle scrolloff with ,z
nnoremap <silent> <Leader>z :let &scrolloff=999-&scrolloff<CR>

" Hilight current line
set cursorline

" Toggle column hilight with ,c
nnoremap <Silent> <Leader>c :set cursorcolumn!<CR>

" Try to save swapfiles in ~/.vim/swap, save in current dir if it fails
set directory^=$HOME/.vim/swap//,.

" Molokai (monokai from textmate)
colors molokai
set background=light


" Fix backspace in insert mode
set backspace=2

" Disable paste mode when leaving Insert Mode
au InsertLeave * set nopaste

" Open new splits to the right/bottom
set splitright splitbelow

" Always show status/power-line
set laststatus=2

" bash-like bindings for vim's command line
cnoremap <C-a>  <Home>
cnoremap <C-b>  <Left>
cnoremap <C-f>  <Right>
cnoremap <C-d>  <Delete>
cnoremap <M-b>  <S-Left>
cnoremap <M-f>  <S-Right>
cnoremap <M-d>  <S-right><Delete>
cnoremap <Esc>b <S-Left>
cnoremap <Esc>f <S-Right>
cnoremap <Esc>d <S-right><Delete>
cnoremap <C-g>  <C-c>

" ...
command WQ wq
command Wq wq
command W w
command Q q

" (Hopefully) removes the delay when hitting esc in insert mode
set noesckeys
set ttimeout
set ttimeoutlen=1

" Fix arrow keys for code completion
set nocompatible

" Statusline
" %F - Longer path
" %r readonly flag
" %m modified flag
" %y filetype
" %c column
" %l line
" %L number of lines
" %P percentage through buffer
" %= right side
set statusline=%F%r%m\ %y%=%{fugitive#head()}\ 0x%B\ %c\ %l/%L\ %P

" Disable double leader in EasyMotion
let g:EasyMotion_leader_key = '<Leader>'

" Make multi cursors not annoying
let g:multi_cursor_exit_from_insert_mode = 0
let g:multi_cursor_exit_from_visual_mode = 0

" Hide git gutter by default
let g:gitgutter_enabled = 0

" f12 to show line numbers and git gutter
map <F12> :set number!<CR>:GitGutterToggle<CR>
inoremap <F12> <Esc>:set number!<CR>:GitGutterToggle<CR>i

" Better tab completion
set wildmenu

" tabs are 4 spaces
set tabstop=4

" ,t for new tab
nnoremap <leader>t <Esc>:tabnew<CR>

" Indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd ctermbg=234
hi IndentGuidesEven ctermbg=235
set wildignore+=*bower_components,node_modules,webroot,tmp

" Use the silver search instead of slow ack
let g:ackprg = 'ag --vimgrep'

" Syntastic
let g:syntastic_python_checkers = ['pyflakes']
let g:syntastic_javascript_checkers = ['jscs', 'jshint']
let g:syntastic_scss_checkers = ['scss_lint']
let g:syntastic_css_checkers = ['csslint']
let g:syntastic_aggregate_errors = 1

" Jira
let g:jiracomplete_url = { 'url': 'http://tickets.int.prnw.net/', 'verify': 'False' }
let g:jiracomplete_username = 'jhedman'
imap <silent> <unique> <leader>j <Plug>JiraComplete

" Title
set title
set titlestring=VIM:\ %-25.55F\ %a%r%m titlelen=70

" fugitive git bindings
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit -v -q<CR>
nnoremap <leader>gt :Gcommit -v -q %:p<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>ge :Gedit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR><CR>
nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
nnoremap <leader>gp :Ggrep<Space>
nnoremap <leader>gm :Gmove<Space>
nnoremap <leader>gbr :Git branch<Space>
nnoremap <leader>gbl :Gblame<CR>
nnoremap <leader>go :Git checkout<Space>
nnoremap <leader>gps :Dispatch! git push<CR>
nnoremap <leader>gpl :Dispatch! git pull<CR>

" Kill all splits except focused
nnoremap <leader>o :only<CR>

" jköl it is
noremap ö l
noremap l k
noremap k j
noremap j h

" Yank to system clipboard (PRIMARY)
set clipboard=unnamed

" ,p to paste from system clipboard (CLIPBOARD)
nmap <leader>p "+p
