# Enable stuff like 'ls *.(html|css|js)'
setopt extended_glob

export PATH=$PATH:~/bin

# mkdir + cd = mkcd
function mkcd {
	dir="$*";
	mkdir -p "$dir" && cd "$dir";
}

# Prompt
PROMPT="%# "
RPROMPT="%n@%m %~ %*"

alias ls="ls -G"
alias l="ls -alh"
alias pyhttpd="python -m SimpleHTTPServer"

# Load plugins and user conf
source ~/dotfiles/zsh/plugins/*
source ~/dotfiles/zsh/custom/^(README.md|.gitignore)

# Delete key
bindkey "^[[3~" delete-char

# Arrow up/down
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt inc_append_history
setopt share_history

# Tab completion
autoload -U compinit
compinit

# % cd dir -> % dir
setopt AUTO_CD

# Spell check (Sometimes annoying)
setopt CORRECT

setopt GLOB_COMPLETE
export EDITOR="vim"
setopt NO_BEEP
setopt NO_CASE_GLOB

# 22 > 3
setopt NUMERIC_GLOB_SORT

# generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, menu it!
zstyle ':completion:*:default' menu 'select=0'

# Have the newer files last so I see them first
zstyle ':completion:*' file-sort modification reverse

# Don't complete stuff already on the line
zstyle ':completion::*:(rm|vi):*' ignore-line true

unsetopt LIST_AMBIGUOUS
setopt  COMPLETE_IN_WORD

# Separate man page sections.  Neat.
zstyle ':completion:*:manuals' separate-sections true

# If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS

# Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

# Pretty    Obvious.  Right?
setopt HIST_REDUCE_BLANKS

# If a line starts with a space, don't save it.
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE

# Save the time and how long a command ran
setopt EXTENDED_HISTORY
